GET http://localhost:8080/api/users/1
###

GET http://localhost:8080/api/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJBRE1JTiIsIlVTRVIiXSwiaWQiOjEsImxvZ2luIjoiYWRtaW4iLCJleHAiOjE3MzA0ODI3OTQsImlhdCI6MTczMDM5NjM5NH0.OZTAUUXa7qddR9DLXPhIBlO1J-mEkIBqajqCMtP33tE
###

POST http://localhost:8080/api/auth
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}
